---
- name: Manually set system time
  hosts: all
  become: true
  tasks:
    - name: Disable NTP synchronization
      ansible.builtin.command: timedatectl set-ntp false
      # This prevents automatic updates from overriding your manual setting
      when: time_sync == 'false'

    - name: Set system date and time| "2026-04-07 15:50:00"
      ansible.builtin.command: timedatectl set-time "2026-04-07 15:50:00"
      # Format: "YYYY-MM-DD HH:MM:SS"
      when: time_sync == 'false'

    - name: Enable NTP synchronization
      ansible.builtin.command: timedatectl set-ntp true
      # This prevents automatic updates from overriding your manual setting
      when: time_sync |bool

    # - name: add a pause of 4 sec to syetem can sync time
    #   ansible.builtin.pause:
    #     seconds: 4
    #   when: time_sync |bool
