---
- name: setup cron jobs
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Ensure cron job is present
      cron:
        name: "My Cron Job"
        minute: "*"
        hour: "*"
        user: root
        job: "df -h>> /var/log/my_script.log 2>&1"
        state: present

    - name: Ensure cron job is present
      cron:
        name: "Cron Job"
        minute: "*"
        hour: "*/2"
        user: root
        job: "df -h>> /var/log/my_script.log 2>&1"
        state: present
