---
- name: "manage cron job for thought generator"
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: copy thought generator script to remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/opt/{{ item }}"
        mode: '0755'
        owner: root
        group: root
      loop:
        - "thought.jar"
        - "LogGenerator.jar"
          
    - name: "Create cron job to execute thought generator every hour"
      ansible.builtin.cron:
        name: "{{item}} Generator"
        minute: "0"
        hour: "*"
        state: "{{cron_state | default('present')}}"
        job: >
          "date -u +%Y-%m-%dT%H:%M:%S >> /var/log/{{item}}.log 2>&1 &&
          java -jar /opt/{{item}} >> /var/log/{{ item }}.log 2>&1"
      loop:
        - "thought.jar"
        - "LogGenerator.jar" 

      