---
- name: Detect and fix PermitRootLogin yes in all SSH config files
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Find all files with 'PermitRootLogin yes'
      ansible.builtin.shell: "grep -Elr '^\\s*PermitRootLogin\\s+yes' /etc/ssh/ || true"
      register: permitrootlogin_files
      changed_when: false

    - name: Show the list of files (if any)
      ansible.builtin.debug:
        msg: >
          {% if permitrootlogin_files.stdout %}
            ⚠️ The following files contain 'PermitRootLogin yes':
            {{ permitrootlogin_files.stdout_lines | join('\n') }}
          {% else %}
            ✅ No files contain 'PermitRootLogin yes'
          {% endif %}

    - name: Update PermitRootLogin to no using lineinfile
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        regexp: 'PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        #backrefs: yes
        #backup: yes
      loop: "{{ permitrootlogin_files.stdout_lines }}"
      when: permitrootlogin_files.stdout != ""
      notify: Restart SSH

    - name: Update PermitRootLogin to no using lineinfile
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '#PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backrefs: yes
        backup: yes
#      loop: "{{ permitrootlogin_files.stdout_lines }}"
      when: permitrootlogin_files.stdout == ""
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted